"use client";
import {useEffect,useState} from "react";
type Rec={id:string,name:string,mobile:string,amount:string|number,mode:"UPI"|"Cash"|"Bank",utr:string,date:string,receivedBy:string,purpose:string,notes:string};
type Audit={id:string,recordId:string,action:string,createdAt:string};
const empty={name:"",mobile:"",amount:"",mode:"UPI",utr:"",date:new Date().toISOString().slice(0,10),receivedBy:"",purpose:"Donation",notes:""};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
export default function Admin(){
 const[auth,setAuth]=useState<boolean|null>(null),[password,setPassword]=useState(""),[records,setRecords]=useState<Rec[]>([]),[audit,setAudit]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null);
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/records",{cache:"no-store"}),fetch("/api/audit",{cache:"no-store"})]);if(a.ok)setRecords(await a.json());if(b.ok)setAudit(await b.json())}finally{setLoading(false)}}
 async function check(){const r=await fetch("/api/auth/me",{cache:"no-store"});const x=await r.json();setAuth(!!x.authenticated);if(x.authenticated)load()}
 useEffect(()=>{check()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok){setPassword("");setAuth(true);await load()}else setMessage("Invalid admin password.");setBusy(false)}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setAuth(false);setRecords([]);setAudit([])}
 function edit(r:Rec){setEditing(r.id);setForm({...r,amount:String(r.amount)})}
 function reset(){setEditing(null);setForm({...empty,date:new Date().toISOString().slice(0,10)})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const url=editing?"/api/records/"+editing:"/api/records";const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const x=await r.json().catch(()=>({}));if(r.ok){reset();await load();setMessage(editing?"Record updated.":"Record added.")}else setMessage(x.error||"Unable to save record.");setBusy(false)}
 async function remove(id:string){if(!window.confirm("Delete this collection record? This action cannot be undone."))return;setBusy(true);const r=await fetch("/api/records/"+id,{method:"DELETE"});const x=await r.json().catch(()=>({}));setMessage(r.ok?"Record deleted.":x.error||"Unable to delete record.");await load();setBusy(false)}
 if(auth===null)return <main className="adminPage"><div className="adminCard"><h1>Admin Dashboard</h1><p>Checking secure session…</p></div></main>;
 if(!auth)return <main className="adminPage"><form className="adminCard" onSubmit={login}><div className="eyebrow">MAA LAXMI PUJA COMMITTEE</div><h1>Admin Dashboard</h1><p>Sign in to manage collection records.</p><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{message&&<div className="error">{message}</div>}<a href="/">← Public collection</a></form></main>;
 const total=records.reduce((a,r)=>a+Number(r.amount),0);
 return <main className="adminPage"><header><div><div className="eyebrow">SECURE COMMITTEE AREA</div><h1>Admin Dashboard</h1><p>Manage the 2026 collection ledger.</p></div><div className="headerActions"><a className="secondary" href="/">Public view</a><button className="secondary" onClick={logout}>Sign out</button></div></header>
 <section className="stats stats3d"><Stat t="Total Collection" v={money(total)}/><Stat t="Records" v={String(records.length)}/><Stat t="UPI" v={money(records.filter(r=>r.mode==="UPI").reduce((a,r)=>a+Number(r.amount),0))}/><Stat t="Cash" v={money(records.filter(r=>r.mode==="Cash").reduce((a,r)=>a+Number(r.amount),0))}/><Stat t="Bank" v={money(records.filter(r=>r.mode==="Bank").reduce((a,r)=>a+Number(r.amount),0))}/></section>
 <section className="card adminCardWide"><div className="sectionHead"><div><div className="eyebrow">{editing?"EDIT RECORD":"ADD RECORD"}</div><h2>{editing?"Update Collection Record":"New Collection Record"}</h2></div>{editing&&<button className="secondary" onClick={reset}>Cancel</button>}</div>
 <form className="adminForm" onSubmit={save}><input placeholder="Contributor name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option>UPI</option><option>Cash</option><option>Bank</option></select><input placeholder="UPI Reference / UTR (optional)" value={form.utr} onChange={e=>setForm({...form,utr:e.target.value})}/><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input placeholder="Received by" value={form.receivedBy} onChange={e=>setForm({...form,receivedBy:e.target.value})}/><select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}><option>Member Fee</option><option>Donation</option><option>Other</option></select><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="primary" disabled={busy}>{busy?"Saving…":editing?"Update Record":"Add Record"}</button></form>{message&&<div className="error">{message}</div>}</section>
 <section className="card adminCardWide"><div className="sectionHead"><div><div className="eyebrow">RECORD MANAGEMENT</div><h2>Collection Records</h2></div><button className="secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="empty">Loading…</div>:<div className="tableWrap"><table><thead><tr><th>Date</th><th>Contributor</th><th>Amount</th><th>Mode</th><th>Type</th><th>Received By</th><th>Actions</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.name||"Anonymous"}<br/><small>{r.mobile||"No mobile"}</small></td><td><b>{money(Number(r.amount))}</b></td><td>{r.mode}</td><td>{r.purpose||"Other"}</td><td>{r.receivedBy||"—"}</td><td><button className="secondary tableAction" onClick={()=>edit(r)}>Edit</button> <button className="danger tableAction" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table>{!records.length&&<div className="empty">No records yet.</div>}</div>}</section>
 <section className="card adminCardWide"><div className="eyebrow">AUDIT HISTORY</div><h2>Recent Changes</h2>{audit.length?<div className="auditList">{audit.map(a=><div className="auditRow" key={a.id}><b>{a.action}</b><span>{a.recordId.slice(0,8)}…</span><small>{new Date(a.createdAt).toLocaleString("en-IN")}</small></div>)}</div>:<div className="empty">No audit entries yet.</div>}</section>
 </main>}
function Stat({t,v}:{t:string,v:string}){return <div className="stat"><span>{t}</span><b>{v}</b></div>}
