"use client";
import {useEffect,useState} from "react";
type Rec={id:string,name:string,mobile:string,amount:string|number,mode:"UPI"|"Cash"|"Bank",utr:string,date:string,receivedBy:string,purpose:string,notes:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
export default function Admin(){
 const[auth,setAuth]=useState<boolean|null>(null),[password,setPassword]=useState(""),[records,setRecords]=useState<Rec[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function check(){const r=await fetch("/api/auth/me",{cache:"no-store"});const x=await r.json();setAuth(!!x.authenticated);if(x.authenticated)load()}
 async function load(){setLoading(true);try{const r=await fetch("/api/records",{cache:"no-store"});if(r.ok)setRecords(await r.json())}finally{setLoading(false)}}
 useEffect(()=>{check()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok){setPassword("");setAuth(true);await load()}else setMessage("Invalid admin password.");setBusy(false)}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setAuth(false);setRecords([])}
 if(auth===null)return <main className="adminPage"><div className="adminCard"><h1>Admin Dashboard</h1><p>Checking secure session…</p></div></main>;
 if(!auth)return <main className="adminPage"><form className="adminCard" onSubmit={login}><div className="eyebrow">MAA LAXMI PUJA COMMITTEE</div><h1>Admin Dashboard</h1><p>Sign in to manage collection records.</p><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{message&&<div className="error">{message}</div>}<a href="/">← Public collection</a></form></main>;
 const total=records.reduce((a,r)=>a+Number(r.amount),0);
 return <main className="adminPage"><header><div><div className="eyebrow">SECURE COMMITTEE AREA</div><h1>Admin Dashboard</h1><p>Manage and review the 2026 collection ledger.</p></div><div className="headerActions"><a className="secondary" href="/">Public view</a><button className="secondary" onClick={logout}>Sign out</button></div></header><section className="stats stats3d"><Stat t="Total Collection" v={money(total)}/><Stat t="Records" v={String(records.length)}/><Stat t="UPI" v={money(records.filter(r=>r.mode==="UPI").reduce((a,r)=>a+Number(r.amount),0))}/><Stat t="Cash" v={money(records.filter(r=>r.mode==="Cash").reduce((a,r)=>a+Number(r.amount),0))}/><Stat t="Bank" v={money(records.filter(r=>r.mode==="Bank").reduce((a,r)=>a+Number(r.amount),0))}/></section><section className="card adminCardWide"><div className="sectionHead"><div><div className="eyebrow">RECORD MANAGEMENT</div><h2>Collection Records</h2></div><button className="secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="empty">Loading…</div>:<div className="tableWrap"><table><thead><tr><th>Date</th><th>Contributor</th><th>Amount</th><th>Mode</th><th>Type</th><th>Received By</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.name||"Anonymous"}<br/><small>{r.mobile||"No mobile"}</small></td><td><b>{money(Number(r.amount))}</b></td><td>{r.mode}</td><td>{r.purpose||"Other"}</td><td>{r.receivedBy||"—"}</td></tr>)}</tbody></table>{!records.length&&<div className="empty">No records yet.</div>}</div>}</section></main>}
function Stat({t,v}:{t:string,v:string}){return <div className="stat"><span>{t}</span><b>{v}</b></div>}
