"use client";
import {useEffect,useState} from "react";
type Rec={id:string,name:string,mobile:string,amount:string|number,mode:"UPI"|"Cash"|"Bank",utr:string,date:string,receivedBy:string,purpose:string,notes:string};
type Audit={id:string,recordId:string,action:string,createdAt:string};
(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
const empty={name:"",mobile:"",amount:"",mode:"UPI",utr:"",date:indiaDate(),receivedBy:"",purpose:"Donation",notes:""};
const indiaDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());\nconst indiaMonth=()=>indiaDate().slice(0,7);
export default function Admin(){
 const[auth,setAuth]=useState<boolean|null>(null),[password,setPassword]=useState(""),[records,setRecords]=useState<Rec[]>([]),[audit,setAudit]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[reportMonth,setReportMonth]=useState(indiaMonth()),[adminQ,setAdminQ]=useState(""),[adminFrom,setAdminFrom]=useState(""),[adminTo,setAdminTo]=useState(""),[adminMode,setAdminMode]=useState("All"),[adminType,setAdminType]=useState("All");
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/records",{cache:"no-store"}),fetch("/api/audit",{cache:"no-store"})]);if(a.ok)setRecords(await a.json());if(b.ok)setAudit(await b.json())}finally{setLoading(false)}}
 async function check(){const r=await fetch("/api/auth/me",{cache:"no-store"});const x=await r.json();setAuth(!!x.authenticated);if(x.authenticated)load()}
 useEffect(()=>{check()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok){setPassword("");setAuth(true);await load()}else setMessage("Invalid admin password.");setBusy(false)}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setAuth(false);setRecords([]);setAudit([])}
 function edit(r:Rec){setEditing(r.id);setForm({...r,amount:String(r.amount)})}
 function reset(){setEditing(null);setForm({...empty,date:indiaDate()})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const normalizedUtr=String(form.utr||"").trim().toLowerCase();if(normalizedUtr){const duplicate=records.find(r=>r.id!==editing&&r.mode==="UPI"&&String(r.utr||"").trim().toLowerCase()===normalizedUtr);if(duplicate){setMessage("Duplicate UPI UTR: this reference is already recorded.");setBusy(false);return}}const url=editing?"/api/records/"+editing:"/api/records";const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const x=await r.json().catch(()=>({}));if(r.ok){reset();await load();setMessage(editing?"Record updated.":"Record added.")}else setMessage(x.error||"Unable to save record.");setBusy(false)}
 async function remove(id:string){if(!window.confirm("Delete this collection record? This action cannot be undone."))return;setBusy(true);const r=await fetch("/api/records/"+id,{method:"DELETE"});const x=await r.json().catch(()=>({}));setMessage(r.ok?"Record deleted.":x.error||"Unable to delete record.");await load();setBusy(false)}
 if(auth===null)return <main className="adminPage"><div className="adminCard"><h1>Admin Dashboard</h1><p>Checking secure session…</p></div></main>;
 if(!auth)return <main className="adminPage"><form className="adminCard" onSubmit={login}><div className="eyebrow">MAA LAXMI PUJA COMMITTEE</div><h1>Admin Dashboard</h1><p>Sign in to manage collection records.</p><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{message&&<div className="error">{message}</div>}<a href="/">← Public collection</a></form></main>;
 const reportRecords=records.filter(r=>r.date.slice(0,7)===reportMonth);
 const reportTotal=reportRecords.reduce((a,r)=>a+Number(r.amount),0);
 const reportBy=(m:string)=>reportRecords.filter(r=>r.mode===m).reduce((a,r)=>a+Number(r.amount),0);
 const reportType=(p:string)=>reportRecords.filter(r=>(r.purpose||"Other")===p).reduce((a,r)=>a+Number(r.amount),0);
 function reportCsv(){const esc=(x:any)=>JSON.stringify(String(x??"")),head=["Date","Contributor","Mobile","Amount","Mode","UTR","Collection Type","Received By","Notes"],body=reportRecords.map(r=>[r.date,r.name,r.mobile,r.amount,r.mode,r.utr,r.purpose,r.receivedBy,r.notes].map(esc).join(","));const blob=new Blob([head.map(esc).join(",")+"\n"+body.join("\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="maa-laxmi-puja-report-"+reportMonth+".csv";a.click();URL.revokeObjectURL(a.href)}
 function printReport(){window.print()}
 const adminFiltered=records.filter(r=>{
  const q=adminQ.toLowerCase().trim();
  const text=[r.name,r.mobile,r.utr,r.receivedBy,r.purpose,r.notes].join(" ").toLowerCase();
  return (!q||text.includes(q))&&(!adminFrom||r.date>=adminFrom)&&(!adminTo||r.date<=adminTo)&&(adminMode==="All"||r.mode===adminMode)&&(adminType==="All"||r.purpose===adminType);
 });
 const total=records.reduce((a,r)=>a+Number(r.amount),0);
 return <main className="adminPage"><header><div><div className="eyebrow">SECURE COMMITTEE AREA</div><h1>Admin Dashboard</h1><p>Manage the 2026 collection ledger.</p></div><div className="headerActions"><a className="secondary" href="/">Public view</a><button className="secondary" onClick={logout}>Sign out</button></div></header>
 <section className="stats stats3d"><Stat t="Total Collection" v={money(total)}/><Stat t="Records" v={String(records.length)}/><Stat t="UPI" v={money(records.filter(r=>r.mode==="UPI").reduce((a,r)=>a+Number(r.amount),0))}/><Stat t="Cash" v={money(records.filter(r=>r.mode==="Cash").reduce((a,r)=>a+Number(r.amount),0))}/><Stat t="Bank" v={money(records.filter(r=>r.mode==="Bank").reduce((a,r)=>a+Number(r.amount),0))}/></section>
 <section className="card adminCardWide"><div className="sectionHead"><div><div className="eyebrow">{editing?"EDIT RECORD":"ADD RECORD"}</div><h2>{editing?"Update Collection Record":"New Collection Record"}</h2></div>{editing&&<button className="secondary" onClick={reset}>Cancel</button>}</div>
 <form className="adminForm" onSubmit={save}><input placeholder="Contributor name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value,utr:e.target.value==="UPI"?form.utr:""})}><option>UPI</option><option>Cash</option><option>Bank</option></select>{form.mode==="UPI"&&<input placeholder="UPI Reference / UTR (optional)" value={form.utr} onChange={e=>setForm({...form,utr:e.target.value})}/><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input placeholder="Received by" value={form.receivedBy} onChange={e=>setForm({...form,receivedBy:e.target.value})}/><select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}><option>Member Fee</option><option>Donation</option><option>Other</option></select><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="primary" disabled={busy}>{busy?"Saving…":editing?"Update Record":"Add Record"}</button></form>{message&&<div className="error">{message}</div>}</section>
 <section className="card adminCardWide"><div className="sectionHead"><div><div className="eyebrow">RECORD MANAGEMENT</div><h2>Collection Records</h2><p>{adminFiltered.length} of {records.length} records shown</p></div><button className="secondary" onClick={load}>↻ Refresh</button></div><div className="adminFilters"><input placeholder="Search name, mobile, UTR, collector…" value={adminQ} onChange={e=>setAdminQ(e.target.value)}/><label>From<input type="date" value={adminFrom} onChange={e=>setAdminFrom(e.target.value)}/></label><label>To<input type="date" value={adminTo} onChange={e=>setAdminTo(e.target.value)}/></label><label>Mode<select value={adminMode} onChange={e=>setAdminMode(e.target.value)}><option>All</option><option>UPI</option><option>Cash</option><option>Bank</option></select></label><label>Type<select value={adminType} onChange={e=>setAdminType(e.target.value)}><option>All</option><option>Member Fee</option><option>Donation</option><option>Other</option></select></label><button className="secondary" onClick={()=>{setAdminQ("");setAdminFrom("");setAdminTo("");setAdminMode("All");setAdminType("All")}}>Clear</button></div>{loading?<div className="empty">Loading…</div>:<div className="tableWrap"><table><thead><tr><th>Date</th><th>Contributor</th><th>Amount</th><th>Mode</th><th>Type</th><th>Received By</th><th>Actions</th></tr></thead><tbody>{adminFiltered.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.name||"Anonymous"}<br/><small>{r.mobile||"No mobile"}</small></td><td><b>{money(Number(r.amount))}</b></td><td>{r.mode}</td><td>{r.purpose||"Other"}</td><td>{r.receivedBy||"—"}</td><td><button className="secondary tableAction" onClick={()=>edit(r)}>Edit</button> <button className="danger tableAction" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table>{!records.length&&<div className="empty">No records yet.</div>}</div>}</section>
  <section className="card adminCardWide reportCard"><div className="sectionHead"><div><div className="eyebrow">COMMITTEE REPORT</div><h2>Monthly Collection Report</h2><p>Print this report or save it as PDF from your browser.</p></div><label>Month <input type="month" value={reportMonth} onChange={e=>setReportMonth(e.target.value)}/></label></div><div className="reportStats"><Stat t="Collection" v={money(reportTotal)}/><Stat t="Records" v={String(reportRecords.length)}/><Stat t="UPI" v={money(reportBy("UPI"))}/><Stat t="Cash" v={money(reportBy("Cash"))}/><Stat t="Bank" v={money(reportBy("Bank"))}/></div><div className="reportMix"><div><b>Member Fee</b><span>{money(reportType("Member Fee"))}</span></div><div><b>Donation</b><span>{money(reportType("Donation"))}</span></div><div><b>Other</b><span>{money(reportType("Other"))}</span></div></div><div className="reportActions"><button className="primary" onClick={printReport}>Print / Save PDF</button><button className="secondary" onClick={reportCsv}>Export Monthly CSV</button></div><div className="reportPrintOnly"><h1>Maa Laxmi Puja Committee — Puja Collection 2026</h1><h2>Monthly Collection Report: {reportMonth}</h2><p>Total Collection: {money(reportTotal)} • Records: {reportRecords.length}</p><table><thead><tr><th>Date</th><th>Contributor</th><th>Amount</th><th>Mode</th><th>Type</th><th>Received By</th></tr></thead><tbody>{reportRecords.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.name||"Anonymous"}</td><td>{money(Number(r.amount))}</td><td>{r.mode}</td><td>{r.purpose||"Other"}</td><td>{r.receivedBy||"—"}</td></tr>)}</tbody></table></div></section> <section className="card adminCardWide"><div className="eyebrow">AUDIT HISTORY</div><h2>Recent Changes</h2>{audit.length?<div className="auditList">{audit.map(a=><div className="auditRow" key={a.id}><b>{a.action}</b><span>{a.recordId.slice(0,8)}…</span><small>{new Date(a.createdAt).toLocaleString("en-IN")}</small></div>)}</div>:<div className="empty">No audit entries yet.</div>}</section>
 </main>}
function Stat({t,v}:{t:string,v:string}){return <div className="stat"><span>{t}</span><b>{v}</b></div>}
