"use client";
import {useEffect,useMemo,useState} from "react";
type Rec={id:string,name:string,mobile:string,amount:string|number,mode:"UPI"|"Cash"|"Bank",utr:string,date:string,receivedBy:string,purpose:string,notes:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
const indiaDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const indiaMonth=()=>indiaDate().slice(0,7);
const mask=(v:string)=>v?v.length>4?"••••"+v.slice(-4):"••••":"—";
export default function Home(){
 const[records,setRecords]=useState<Rec[]>([]),[q,setQ]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[modeFilter,setModeFilter]=useState("All"),[purposeFilter,setPurposeFilter]=useState("All"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[shared,setShared]=useState(false),[ready,setReady]=useState(false),[lastUpdated,setLastUpdated]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/records?q="+encodeURIComponent(q),{cache:"no-store"});if(!r.ok)throw new Error();setRecords(await r.json());setError("");setLastUpdated(new Date().toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}))}catch{setError("Collection records are temporarily unavailable.")}finally{setLoading(false)}}
 useEffect(()=>{const p=new URLSearchParams(location.search);setQ(p.get("q")||"");setDateFrom(p.get("from")||"");setDateTo(p.get("to")||"");setModeFilter(p.get("mode")||"All");setPurposeFilter(p.get("type")||"All");setReady(true)},[]);
 useEffect(()=>{load()},[q]);
 useEffect(()=>{if(!ready)return;const p=new URLSearchParams();if(q)p.set("q",q);if(dateFrom)p.set("from",dateFrom);if(dateTo)p.set("to",dateTo);if(modeFilter!=="All")p.set("mode",modeFilter);if(purposeFilter!=="All")p.set("type",purposeFilter);const next=p.toString()?location.pathname+"?"+p.toString():location.pathname;history.replaceState(null,"",next)},[ready,q,dateFrom,dateTo,modeFilter,purposeFilter]);
 const filtered=useMemo(()=>records.filter(r=>(!dateFrom||r.date>=dateFrom)&&(!dateTo||r.date<=dateTo)&&(modeFilter==="All"||r.mode===modeFilter)&&(purposeFilter==="All"||r.purpose===purposeFilter)),[records,dateFrom,dateTo,modeFilter,purposeFilter]);
 const total=filtered.reduce((a,r)=>a+Number(r.amount),0),today=filtered.filter(r=>r.date===indiaDate()).reduce((a,r)=>a+Number(r.amount),0);
 const by=(m:string)=>filtered.filter(r=>r.mode===m).reduce((a,r)=>a+Number(r.amount),0);
 const contributors=useMemo(()=>{const m=new Map<string,number>();filtered.forEach(r=>{const n=r.name?.trim()||"Anonymous";m.set(n,(m.get(n)||0)+Number(r.amount))});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)},[filtered]);
 const timeline=useMemo(()=>{const m=new Map<string,number>();filtered.forEach(r=>m.set(r.date,(m.get(r.date)||0)+Number(r.amount)));return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-7)},[filtered]);
 const maxDay=Math.max(...timeline.map(x=>x[1]),1);
 const[selectedMonth,setSelectedMonth]=useState(indiaMonth());
 const monthRecords=useMemo(()=>records.filter(r=>r.date.slice(0,7)===selectedMonth),[records,selectedMonth]);
 const monthTotal=monthRecords.reduce((a,r)=>a+Number(r.amount),0);
 const monthBy=(m:string)=>monthRecords.filter(r=>r.mode===m).reduce((a,r)=>a+Number(r.amount),0);
 const monthByType=(p:string)=>monthRecords.filter(r=>(r.purpose||"Other")===p).reduce((a,r)=>a+Number(r.amount),0);
 const previousMonth=useMemo(()=>{const [y,m]=selectedMonth.split("-").map(Number);const d=new Date(Date.UTC(y,m-2,1));return d.toISOString().slice(0,7)},[selectedMonth]);
 const previousMonthTotal=useMemo(()=>records.filter(r=>r.date.slice(0,7)===previousMonth).reduce((a,r)=>a+Number(r.amount),0),[records,previousMonth]);
 const monthChange=previousMonthTotal?((monthTotal-previousMonthTotal)/previousMonthTotal*100):null;
 const monthAverage=monthRecords.length?monthTotal/monthRecords.length:0;
 const largestContribution=monthRecords.length?Math.max(...monthRecords.map(r=>Number(r.amount))):0;
 const uniqueContributors=new Set(monthRecords.map(r=>r.name?.trim()||"Anonymous")).size;
 function csv(){const esc=(x:any)=>JSON.stringify(String(x??"")),head=["Date","Contributor","Amount","Mode","Purpose","Received By"],body=filtered.map(r=>[r.date,r.name,r.amount,r.mode,r.purpose,r.receivedBy].map(esc).join(","));const blob=new Blob([head.map(esc).join(",")+"\n"+body.join("\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="maa-laxmi-puja-collection-2026.csv";a.click();URL.revokeObjectURL(a.href)}
 function clearFilters(){setDateFrom("");setDateTo("");setModeFilter("All");setPurposeFilter("All");setQ("")}
 async function share(){const data={title:"Maa Laxmi Puja Collection 2026",text:"View the Maa Laxmi Puja Committee collection record.",url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);setShared(true);setTimeout(()=>setShared(false),1800)}}catch{}}
 return <main>
  <header><div><div className="eyebrow">MAA LAXMI PUJA COMMITTEE</div><h1>🪔 Puja Collection <span>2026</span></h1><p>Official collection record • Transparent view for committee members</p></div><div className="headerActions"><button className="secondary" onClick={share}>{shared?"✓ Link copied":"↗ Share"}</button><button className="secondary" onClick={load}>↻ Refresh</button></div></header>
  <section className="hero3d"><div className="heroGlow heroGlowOne"></div><div className="heroGlow heroGlowTwo"></div><div className="hero3dInner"><div className="heroCopy"><div className="eyebrow">2026 • OFFICIAL COMMUNITY LEDGER</div><h2>Celebrate together.<br/><span>Keep every contribution transparent.</span></h2><p>A modern public record for the Maa Laxmi Puja Committee.</p><a href="#records" className="heroCta">View Collection ↓</a></div><div className="heroScene"><div className="orb orbBack"></div><div className="orb orbFront"></div><div className="diya3d">🪔</div><div className="heroCard heroCardMain"><small>COLLECTION</small><strong>{money(total)}</strong><span>2026 • LIVE RECORD</span></div><div className="heroCard heroCardMini"><b>{filtered.length}</b><span>Records</span></div></div></div></section>
  <div className="notice">ℹ️ <b>Public record:</b> This website displays collection records only. Payments are handled separately through UPI, cash, or bank. No payment is processed on this website.</div>
  <section className="stats stats3d"><Stat t="Total Collection" v={money(total)}/><Stat t="Records" v={String(filtered.length)}/><Stat t="Today's Collection" v={money(today)}/><Stat t="UPI" v={money(by("UPI"))}/><Stat t="Cash" v={money(by("Cash"))}/><Stat t="Bank" v={money(by("Bank"))}/></section>
  <section className="overview3d"><div className="overviewTile"><span>UPI</span><b>{money(by("UPI"))}</b><small>Digital contributions</small></div><div className="overviewTile"><span>Cash</span><b>{money(by("Cash"))}</b><small>Cash collections</small></div><div className="overviewTile"><span>Bank</span><b>{money(by("Bank"))}</b><small>Bank contributions</small></div></section>
  <section className="insights"><div className="insightCard"><div className="sectionHead"><div><div className="eyebrow">COMMUNITY SNAPSHOT</div><h2>Collection Insights</h2></div><span className="liveDot">● LIVE</span></div><div className="chart">{timeline.length?timeline.map(([d,v])=><div className="barItem" key={d}><div className="barValue">{money(v)}</div><div className="barTrack"><div className="barFill" style={{height:`${Math.max(8,v/maxDay*100)}%`}}/></div><small>{d.slice(5)}</small></div>):<div className="empty">No timeline data yet.</div>}</div></div>
   <div className="insightCard"><div className="sectionHead"><div><div className="eyebrow">TOP CONTRIBUTORS</div><h2>Community Support</h2></div></div>{contributors.length?contributors.map(([n,v],i)=><div className="leader" key={n}><span className="rank">{i+1}</span><div><b>{n}</b><small>Contribution recorded</small></div><strong>{money(v)}</strong></div>):<div className="empty">No contributors yet.</div>}</div></section>
  <section className="insights monthlyDashboard"><div className="insightCard"><div className="sectionHead"><div><div className="eyebrow">MONTHLY REPORT</div><h2>Collection Dashboard</h2></div><label>Month <input type="month" value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)}/></label></div><div className="stats"><Stat t="Monthly Collection" v={money(monthTotal)}/><Stat t="Records" v={String(monthRecords.length)}/><Stat t="Unique Contributors" v={String(uniqueContributors)}/><Stat t="Average Contribution" v={money(monthAverage)}/><Stat t="Largest Contribution" v={money(largestContribution)}/><Stat t="UPI" v={money(monthBy("UPI"))}/><Stat t="Cash" v={money(monthBy("Cash"))}/><Stat t="Bank" v={money(monthBy("Bank"))}/></div><div className="monthCompare"><span>vs previous month</span><b>{monthChange===null?"No previous-month data":`${monthChange>=0?"+":""}${monthChange.toFixed(1)}%`}</b><small>{previousMonthTotal?`${money(previousMonthTotal)} in ${previousMonth}`:"No recorded collection in previous month"}</small></div></div><div className="insightCard"><div className="sectionHead"><div><div className="eyebrow">BREAKDOWN</div><h2>Monthly Collection Mix</h2></div></div>{["Member Fee","Donation","Other"].map(p=><div className="mixRow" key={p}><span>{p}</span><div className="mixTrack"><div className="mixFill" style={{width:((monthTotal?Math.min(100,monthByType(p)/monthTotal*100):0)+"%")}}/></div><b>{money(monthByType(p))}</b></div>)}{!monthRecords.length&&<div className="empty">No records for this month.</div>}</div></section>
  <section className="miniInsights"><div className="miniCard"><div className="eyebrow">COLLECTION MIX</div><h2>Where contributions come from</h2>{["Member Fee","Donation","Other"].map(p=><div className="mixRow" key={p}><span>{p}</span><div className="mixTrack"><div className="mixFill" style={{width:((total?Math.min(100,filtered.filter(r=>r.purpose===p).reduce((a,r)=>a+Number(r.amount),0)/total*100):0)+"%")}}/></div><b>{money(filtered.filter(r=>r.purpose===p).reduce((a,r)=>a+Number(r.amount),0))}</b></div>)}</div><div className="miniCard"><div className="eyebrow">RECENT ACTIVITY</div><h2>Latest records</h2>{filtered.slice(0,5).map(r=><div className="recentRow" key={r.id}><div><b>{r.name||"Anonymous"}</b><small>{r.date} • {r.purpose||"Other"}</small></div><strong>{money(Number(r.amount))}</strong></div>)}{!filtered.length&&<div className="empty">No recent records.</div>}</div></section>
  <section className="grid"><div id="records" className="card records" style={{gridColumn:"1 / -1"}}>
   <div className="toolbar"><div><div className="eyebrow">COLLECTION LEDGER</div><h2>Collection Records</h2><p>{filtered.length} of {records.length} record{records.length===1?"":"s"} shown {lastUpdated&&<><br/><small>Last refreshed: {lastUpdated}</small></>}</p></div><div className="toolbarBtns"><input aria-label="Search records" placeholder="Search contributor or collection type..." value={q} onChange={e=>setQ(e.target.value)}/><button className="secondary" onClick={clearFilters}>Clear</button><button className="secondary" onClick={()=>window.print()}>Print</button><button className="secondary" onClick={csv}>CSV</button></div></div>
   <div className="filters"><label>From<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>To<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><label>Mode<select value={modeFilter} onChange={e=>setModeFilter(e.target.value)}><option>All</option><option>UPI</option><option>Cash</option><option>Bank</option></select></label><label>Collection Type<select value={purposeFilter} onChange={e=>setPurposeFilter(e.target.value)}><option>All</option><option>Member Fee</option><option>Donation</option><option>Other</option></select></label></div>
   {error&&<div className="error">{error} <button className="secondary" onClick={load}>Try again</button></div>}
   <div className="tableWrap"><table><thead><tr><th>Date</th><th>Contributor</th><th>Amount</th><th>Mode</th><th>UTR</th><th>Collection Type</th><th>Received By</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.date}</td><td><b>{r.name||"Anonymous"}</b><br/><small>{mask(r.mobile)}</small></td><td><b>{money(Number(r.amount))}</b></td><td><span className={"pill "+r.mode.toLowerCase()}>{r.mode}</span></td><td>{mask(r.utr)}</td><td>{r.purpose||"Other"}</td><td>{r.receivedBy||"—"}</td></tr>)}</tbody></table>{loading?<div className="empty">Loading collection records…</div>:!filtered.length&&<div className="empty">No collection records match the selected filters.</div>}</div>
   <div className="publicNote">🔒 Personal mobile numbers and UPI references are partially masked for privacy.</div>
  </div></section>
  <section className="howItWorks"><div className="howIntro"><div className="eyebrow">TRANSPARENCY FIRST</div><h2>How this collection record works</h2><p>This portal is designed for visibility and record keeping. It does not collect or process payments.</p></div><div className="steps"><div className="step"><span>01</span><b>Contribution received</b><small>UPI, cash or bank contribution is handled separately by the committee.</small></div><div className="step"><span>02</span><b>Record added</b><small>The committee records the contribution with its date, type and payment mode.</small></div><div className="step"><span>03</span><b>Community view</b><small>Members can review the public ledger with sensitive details partially masked.</small></div></div></section>
  <section className="devotional"><div className="devotionalGlow"></div><div><div className="eyebrow">🪷 MAA LAXMI PUJA • 2026</div><h2>May Maa Laxmi bless every home with peace and prosperity.</h2><p>Thank you to every member, donor and volunteer supporting this year's community celebration.</p></div><a href="#records" className="heroCta">View Records</a></div></section>
  <footer>🪔 Maa Laxmi Puja Committee • Puja Collection 2026 • Public record-only system</footer>
 </main>
}
function Stat({t,v}:{t:string,v:string}){return <div className="stat"><span>{t}</span><b>{v}</b></div>}
