"use client";
import {useEffect,useMemo,useState} from "react";
type Rec={id:string,name:string,mobile:string,amount:string|number,mode:"UPI"|"Cash"|"Bank",utr:string,date:string,receivedBy:string,purpose:string,notes:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
const mask=(v:string)=>v? v.length>4?"••••"+v.slice(-4):"••••":"—";
export default function Home(){
 const[records,setRecords]=useState<Rec[]>([]),[q,setQ]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[modeFilter,setModeFilter]=useState("All"),[purposeFilter,setPurposeFilter]=useState("All"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/records?q="+encodeURIComponent(q),{cache:"no-store"});if(!r.ok)throw new Error("Unable to load records");setRecords(await r.json());setError("")}catch(e){setError("Collection records are temporarily unavailable.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[q]);
 const filtered=useMemo(()=>records.filter(r=>(!dateFrom||r.date>=dateFrom)&&(!dateTo||r.date<=dateTo)&&(modeFilter==="All"||r.mode===modeFilter)&&(purposeFilter==="All"||r.purpose===purposeFilter)),[records,dateFrom,dateTo,modeFilter,purposeFilter]);
 const total=filtered.reduce((a,r)=>a+Number(r.amount),0),today=filtered.filter(r=>r.date===new Date().toISOString().slice(0,10)).reduce((a,r)=>a+Number(r.amount),0);
 const by=(m:string)=>filtered.filter(r=>r.mode===m).reduce((a,r)=>a+Number(r.amount),0);
 function csv(){const esc=(x:any)=>JSON.stringify(String(x??"")),head=["Date","Contributor","Amount","Mode","Purpose","Received By"],body=filtered.map(r=>[r.date,r.name,r.amount,r.mode,r.purpose,r.receivedBy].map(esc).join(","));const blob=new Blob([head.map(esc).join(",")+"\n"+body.join("\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="maa-laxmi-puja-collection-2026.csv";a.click();URL.revokeObjectURL(a.href)}
 function clearFilters(){setDateFrom("");setDateTo("");setModeFilter("All");setPurposeFilter("All");setQ("")}
 return <main>
  <header><div><div className="eyebrow">MAA LAXMI PUJA COMMITTEE</div><h1>🪔 Puja Collection <span>2026</span></h1><p>Official collection record • Transparent view for committee members</p></div><button className="secondary" onClick={load}>↻ Refresh</button></header>
  <section className="hero3d"><div className="heroGlow heroGlowOne"></div><div className="heroGlow heroGlowTwo"></div><div className="hero3dInner"><div className="heroCopy"><div className="eyebrow">2026 • OFFICIAL COMMUNITY LEDGER</div><h2>Celebrate together.<br/><span>Keep every contribution transparent.</span></h2><p>A modern public record for the Maa Laxmi Puja Committee.</p><a href="#records" className="heroCta">View Collection ↓</a></div><div className="heroScene"><div className="orb orbBack"></div><div className="orb orbFront"></div><div className="diya3d">🪔</div><div className="heroCard heroCardMain"><small>COLLECTION</small><strong>{money(total)}</strong><span>2026 • LIVE RECORD</span></div><div className="heroCard heroCardMini"><b>{filtered.length}</b><span>Records</span></div></div></div></section><div className="notice">ℹ️ <b>Public record:</b> This website displays collection records only. Payments are handled separately through UPI, cash, or bank. No payment is processed on this website.</div>
  <section className="stats stats3d"><Stat t="Total Collection" v={money(total)}/><Stat t="Records" v={String(filtered.length)}/><Stat t="Today's Collection" v={money(today)}/><Stat t="UPI" v={money(by("UPI"))}/><Stat t="Cash" v={money(by("Cash"))}/><Stat t="Bank" v={money(by("Bank"))}/></section>
  <section className="overview3d"><div className="overviewTile"><span>UPI</span><b>{money(by("UPI"))}</b><small>Digital contributions</small></div><div className="overviewTile"><span>Cash</span><b>{money(by("Cash"))}</b><small>Cash collections</small></div><div className="overviewTile"><span>Bank</span><b>{money(by("Bank"))}</b><small>Bank contributions</small></div></section><section id="records" className="grid"><div className="card records" style={{gridColumn:"1 / -1"}}>
   <div className="toolbar"><div><div className="eyebrow">COLLECTION LEDGER</div><h2>Collection Records</h2><p>{filtered.length} of {records.length} record{records.length===1?"":"s"} shown</p></div><div className="toolbarBtns"><input aria-label="Search records" placeholder="Search contributor, mobile, UTR…" value={q} onChange={e=>setQ(e.target.value)}/><button className="secondary" onClick={clearFilters}>Clear</button><button className="secondary" onClick={()=>window.print()}>Print</button><button className="secondary" onClick={csv}>CSV</button></div></div>
   <div className="filters"><label>From<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>To<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><label>Mode<select value={modeFilter} onChange={e=>setModeFilter(e.target.value)}><option>All</option><option>UPI</option><option>Cash</option><option>Bank</option></select></label><label>Collection Type<select value={purposeFilter} onChange={e=>setPurposeFilter(e.target.value)}><option>All</option><option>Member Fee</option><option>Donation</option><option>Other</option></select></label></div>
   {error&&<div className="error">{error} <button className="secondary" onClick={load}>Try again</button></div>}
   <div className="tableWrap"><table><thead><tr><th>Date</th><th>Contributor</th><th>Amount</th><th>Mode</th><th>UTR</th><th>Collection Type</th><th>Received By</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.date}</td><td><b>{r.name||"Anonymous"}</b><br/><small>{mask(r.mobile)}</small></td><td><b>{money(Number(r.amount))}</b></td><td><span className={"pill "+r.mode.toLowerCase()}>{r.mode}</span></td><td>{mask(r.utr)}</td><td>{r.purpose||"Other"}</td><td>{r.receivedBy||"—"}</td></tr>)}</tbody></table>{loading?<div className="empty">Loading collection records…</div>:!filtered.length&&<div className="empty">No collection records match the selected filters.</div>}</div>
   <div className="publicNote">🔒 Personal mobile numbers and UPI references are partially masked for privacy.</div>
  </div></section>
  <footer>🪔 Maa Laxmi Puja Committee • Puja Collection 2026 • Public record-only system</footer>
 </main>
}
function Stat({t,v}:{t:string,v:string}){return <div className="stat"><span>{t}</span><b>{v}</b></div>}
